[package]
name = "login-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.7", features = ["derive"] }
authentication = { path = "../authentication" }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
